---
- name: Kill Docker Containers
  shell: "docker rm $(docker ps -qa) --force || true"
  become_user: "{{ om_user }}"
  ignore_errors: yes

- name: Build Docker Images
  shell: "docker compose build"
  args:
    chdir: "{{ build_dir }}/packages/grid"
  become_user: "{{ om_user }}"

- name: Remove old Docker Images
  shell: "docker rmi $(docker images -qa -f 'dangling=true') || true"
  become_user: "{{ om_user }}"
  ignore_errors: yes

- name: Start Docker Containers
  shell:
    cmd: runuser -l {{ om_user }} -c 'hagrid launch {{ node_name }} domain to docker:80 --tail=false'
  become: yes
